### ISSUE TITLE
Double tab in C-x C-f moves point to beginning of minibuffer

### ISSUE THREAD

**Issue by sje30** [tarsius/moody#29] opened 2021-05-21 20:30 UTC
Hi,
I've noticed an odd bug, and it seems repeatable for me if I just load straight.el and then have the following config:

```
(use-package moody
  :config
  (setq x-underline-at-descent-line t)
  ;; (moody-replace-mode-line-buffer-identification)
  ;;(moody-replace-vc-mode)
  )
```

From a fresh emacs, if I load straight, and then the above config, moody appears.
If I then do C-x C-f TAB TAB

after the first tab I get [Complete, but not Unique] at the end of the minibuffer; after the second tab  I see a *Completions* buffer with the files in my current directory.  So far so good.

If however I then do M-x moody-replace-vc-mode  the declaration around the Git-master changes, as expected.  However, if I now do C-x C-f TAB TAB

after the second tab, as well ast the completions buffer appearing, point moves to the beginning of the minibuffer (i.e. over the F of "Find file" prompt).

Is this just my config?  I've got an up to date moody.el i think and I'm running

```
(emacs-version)
"GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.28, cairo version 1.17.4)
 of 2021-04-28"
```

Thanks for any help.

**Comment by tarsius** [comment] 2021-05-21 21:57
It seems highly unlikely that moody has anything to do with this. The only thing it does with the minibuffer is to check whether it is active to decide what face to use, and it does nothing that concerns cursor movement.

**Comment by sje30** [comment] 2021-05-22 06:13
Thanks.  Here's a minimal example that reproduces the issue for me, using the latest version of moody.el:

emacs -q f.el

where f.el is simply:

```
(load "~/moody.el")
(moody-replace-mode-line-buffer-identification)
```

and then 
C-x C-f TAB TAB 

I agree its an odd one, are you referring to moody-window-active-p logic?

If you can't replicate it, I'll close this.

**Comment by sje30** [comment] 2021-05-22 06:31
& if I change that predicate to always return t (which I presume will break other things)

```
(load "~/moody.el")
(defun moody-window-active-p  ()
  t)
(moody-replace-mode-line-buffer-identification)
```


then C-x C-f TAB TAB does not move the point to the beginning of the minibuffer, but instead the *Completions* buffer cycles as normal.

**Comment by tarsius** [comment] 2021-05-22 07:28
I can reproduce now and I also found a "fix". I still find this highly surprising.

**Comment by tarsius** [comment] 2021-05-22 11:03
I had to revert because this wrapping lead to bug that is much worse than the one it fixed. Newly created windows would remain blank until pressing C-g.

**Comment by sje30** [comment] 2021-05-22 17:30
ah, okay.  Seems like there some oddities going on here.  thanks for investigating.

**Comment by jthaman** [comment] 2021-07-19 15:50
Is there a workaround or a way to recover from this bug?

**Comment by capfredf** [comment] 2021-07-19 16:37
To recover, you just need to press `C-e`

**Comment by tarsius** [comment] 2021-07-29 12:22
Should be fixed now.

**Closed by tarsius** 2021-07-29 12:22 UTC
